# Generated by Django 3.0.4 on 2020-03-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200326_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': (['due_back'],), 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
