# Generated by Django 3.0.4 on 2020-03-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200326_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_all_books', 'Permission to view all books'),)},
        ),
    ]
