# Generated by Django 3.0.4 on 2020-03-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200326_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_all_books', 'Permission to view all books'), ('can_mark_returned', 'Permission to return books'))},
        ),
    ]
